<h1>Number Helper</h1>
<p>
    The Number Helper file contains functions that help you work with numeric data.
</p>
<h2>Loading this Helper</h2>
<p>
    This helper is loaded using the following code:
</p>
<code>
    $this->load->helper('number');
</code>
<p>
    The following functions are available:
</p>
<h2>byte_format()</h2>
<p>
    Formats a numbers as bytes, based on size, and adds the appropriate suffix.  Examples:
</p>
<code>
    echo byte_format(456); // Returns 456 Bytes
    <br/>
    echo byte_format(4567); // Returns 4.5 KB
    <br/>
    echo byte_format(45678); // Returns 44.8 KB
    <br/>
    echo byte_format(456789); // Returns 447.8 KB
    <br/>
    echo byte_format(3456789); // Returns 3.3 MB
    <br/>
    echo byte_format(12345678912345); // Returns 1.8 GB
    <br/>
    echo byte_format(123456789123456789); // Returns 11,228.3 TB
</code>
<p class="important">
    <strong>Note:</strong>
    The text generated by this function is found in the following language file: language/
    <your_lang>
    /number_lang.php
</p>
